title: Exploring the CS World Log
description: A personal blog documenting my learning journey in computer science, covering topics such as Rust, Docker, Functional Programming, and more.
author:
  name: [Aryan Patel]
  email: [80884675+hugemobster@users.noreply.github.com]
baseurl: ""
url: "https://github.com/[hugemobster]/exploringComSciWorldLog"

theme: "minima" 
paginate: 5

